### ISSUE TITLE
PHP 8.1 Support possible?

### ISSUE THREAD

**Issue by organit** [shyim/ShyimAttributeTransformer#18]
We have issues updating to PHP 8.1 (SW 5.7.16). Is an update possible?

**Comment by shyim** [comment]
whats the error you have?

**Comment by organit** [comment]
Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /var/www/clients/client1/web2/web/custom/plugins/ShyimAttributeTransformer/Components/ModelTransformer.php:56 Stack trace: #0 /var/www/clients/client1/web2/web/custom/plugins/ShyimAttributeTransformer/Components/ModelTransformer.php(56): in_array() #1 /var/www/clients/client1/web2/web/custom/plugins/ShyimAttributeTransformer/Components/AttributeTransformer.php(45): ShyimAttributeTransformer\Components\ModelTransformer->addIds() #2 /var/www/clients/client1/web2/web/custom/plugins/ShyimAttributeTransformer/Components/Converter.php(144): ShyimAttributeTransformer\Components\AttributeTransformer->addAttribute() #3 /var/www/clients/client1/web2/web/custom/plugins/ShyimAttributeTransformer/Components/Converter.php(84): ShyimAttributeTransformer\Components\Converter->transformAttributeFields() #4 /var/www/clients/client1/web2/web/custom/plugins/ShyimAttributeTransformer/Subscriber/LegacyStructConverter.php(61): ShyimAttributeTransformer\Components\Converter->convert() #5 /var/www/clients/client1/web2/web/engine/Library/Enlight/Event/Handler/Default.php(90): ShyimAttributeTransformer\Subscriber\LegacyStructConverter->legacyStructConverter() #6 /var/www/clients/client1/web2/web/engine/Library/Enlight/Event/EventManager.php(291): Enlight_Event_Handler_Default->execute() #7 /var/www/clients/client1/web2/web/engine/Shopware/Components/Compatibility/LegacyStructConverter.php(346): Enlight_Event_EventManager->filter() #8 /var/www/clients/client1/web2/web/engine/Shopware/Core/sArticles.php(2393): Shopware\Components\Compatibility\LegacyStructConverter->convertListProductStruct() #9 /var/www/clients/client1/web2/web/engine/Shopware/Core/sArticles.php(1319): sArticles->getPromotion() #10 /var/www/clients/client1/web2/web/engine/Shopware/Plugins/Community/Frontend/DreiscMenu/Components/DreiscMenu/Model.php(779): sArticles->sGetPromotionById() #11 /var/www/clients/client1/web2/web/engine/Shopware/Plugins/Community/Frontend/DreiscMenu/Components/DreiscMenu/Model.php(599): Shopware_Components_DreiscMenu_Model->getArticleByNumber() #12 /var/www/clients/client1/web2/web/engine/Shopware/Plugins/Community/Frontend/DreiscMenu/Components/DreiscMenu/Model.php(531): Shopware_Components_DreiscMenu_Model->loadMenuRow() #13 /var/www/clients/client1/web2/web/engine/Shopware/Plugins/Community/Frontend/DreiscMenu/Bootstrap.php(713): Shopware_Components_DreiscMenu_Model->loadMenuByCategoryId() #14 /var/www/clients/client1/web2/web/engine/Library/Enlight/Event/Handler/Plugin.php(155): Shopware_Plugins_Frontend_DreiscMenu_Bootstrap->onPostDispatchFrontend() #15 /var/www/clients/client1/web2/web/engine/Library/Enlight/Event/EventManager.php(207): Enlight_Event_Handler_Plugin->execute() #16 /var/www/clients/client1/web2/web/engine/Library/Enlight/Controller/Action.php(229): Enlight_Event_EventManager->notify() #17 /var/www/clients/client1/web2/web/engine/Library/Enlight/Controller/Dispatcher/Default.php(467): Enlight_Controller_Action->dispatch() #18 /var/www/clients/client1/web2/web/engine/Library/Enlight/Controller/Front.php(225): Enlight_Controller_Dispatcher_Default->dispatch() #19 /var/www/clients/client1/web2/web/engine/Shopware/Kernel.php(197): Enlight_Controller_Front->dispatch() #20 /var/www/clients/client1/web2/web/vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(85): Shopware\Kernel->handle() #21 /var/www/clients/client1/web2/web/vendor/symfony/http-kernel/HttpCache/HttpCache.php(479): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle() #22 /var/www/clients/client1/web2/web/engine/Shopware/Components/HttpCache/AppCache.php(266): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward() #23 /var/www/clients/client1/web2/web/vendor/symfony/http-kernel/HttpCache/HttpCache.php(452): Shopware\Components\HttpCache\AppCache->forward() #24 /var/www/clients/client1/web2/web/vendor/symfony/http-kernel/HttpCache/HttpCache.php(346): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch() #25 /var/www/clients/client1/web2/web/engine/Shopware/Components/HttpCache/AppCache.php(192): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup() #26 /var/www/clients/client1/web2/web/vendor/symfony/http-kernel/HttpCache/HttpCache.php(224): Shopware\Components\HttpCache\AppCache->lookup() #27 /var/www/clients/client1/web2/web/engine/Shopware/Components/HttpCache/AppCache.php(117): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle() #28 /var/www/clients/client1/web2/web/shopware.php(122): Shopware\Components\HttpCache\AppCache->handle() #29 {main} thrown in /var/www/clients/client1/web2/web/custom/plugins/ShyimAttributeTransformer/Components/ModelTransformer.php on line 56

**Comment by shyim** [comment]
can you try again? 
https://github.com/shyim/ShyimAttributeTransformer/commit/e8985ca00eb7aa2877a43aad16da6bf296c594b4

**Comment by organit** [comment]
issues solved. thank you very much!
