### ISSUE TITLE
Aufruf einer Form oder Custom Page - No Foreign Key Provided

### ISSUE THREAD

**Issue by marco9876** [shyim/ShyimAttributeTransformer#4]
Kriege diesen Error wenn ich eine Seite aufrufe.  Seite selber funktioniert.
Muss ich die reparieren die Foreign Keys?

Shopware 5.5.7 Litespeed / Apache Mysql 5.5 PHP 7.3 

Exception: No foreign key provided in path/engine/Shopware/Bundle/AttributeBundle/Service/DataLoader.php:71
Stack trace:
#0 path/custom/plugins/ShyimAttributeTransformer/Subscriber/TemplateSubscriber.php(55): Shopware\Bundle\AttributeBundle\Service\DataLoader->load('s_cms_support_a...', NULL)
#1 path/engine/Library/Enlight/Event/Handler/Default.php(91): ShyimAttributeTransformer\Subscriber\TemplateSubscriber->transformForm(Object(Enlight_Controller_ActionEventArgs))
#2 path/engine/Library/Enlight/Event/EventManager.php(220): Enlight_Event_Handler_Default->execute(Object(Enlight_Controller_ActionEventArgs))
#3 path/engine/Library/Enlight/Controller/Action.php(224): Enlight_Event_EventManager->notify('Enlight_Control...', Object(Enlight_Controller_ActionEventArgs))
#4 path/engine/Library/Enlight/Controller/Dispatcher/Default.php(563): Enlight_Controller_Action->dispatch('indexAction')
#5 path/engine/Library/Enlight/Controller/Front.php(222): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))
#6 path/engine/Shopware/Kernel.php(202): Enlight_Controller_Front->dispatch()
#7 path/vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(102): Shopware\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 path/vendor/symfony/http-kernel/HttpCache/HttpCache.php(448): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle(Object(Shopware\Kernel), Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 path/engine/Shopware/Components/HttpCache/AppCache.php(268): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true, NULL)
#10 path/vendor/symfony/http-kernel/HttpCache/HttpCache.php(420): Shopware\Components\HttpCache\AppCache->forward(Object(Symfony\Component\HttpFoundation\Request), true)
#11 path/vendor/symfony/http-kernel/HttpCache/HttpCache.php(317): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true)
#12 path/engine/Shopware/Components/HttpCache/AppCache.php(189): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true)
#13 path/vendor/symfony/http-kernel/HttpCache/HttpCache.php(192): Shopware\Components\HttpCache\AppCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true)
#14 path/engine/Shopware/Components/HttpCache/AppCache.php(116): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 path/shopware.php(122): Shopware\Components\HttpCache\AppCache->handle(Object(Symfony\Component\HttpFoundation\Request))
#16 {main}

**Comment by shyim** [comment]
Hast du vielleicht eine CMS Seite aufgerufen die eine 404 zurückgeben würde?
