### ISSUE TITLE
Fehler mit Shopware 5.6.3

### ISSUE THREAD

**Issue by Sev03** [shyim/ShyimAttributeTransformer#9]
Wenn ich mit 5.6.3 bei den Configurator Options ein Freitextfeld habe (Bild ID), dann erhalte ich den Fehler -> Converter.php (line 66) -> Array erwartet, aber Objekt bekommen.
Liegt daran, dass in dieser Line auf Kategorien Freitextfelder überprüft wird, jedoch hier keine Abfrage ist, ob es sich um ein Object oder Array handelt.
In diesem Fall existiert $data["attribute"], jedoch ist es ein Object -> transformAttributeFields erwartet aber ein Array

// Legacy_Struct_Converter_Convert_Category
if (isset($data['attribute'])) {
            $data['attribute'] = $this->transformAttributeFields($fields, $data['attribute'], $columns);
}

**Comment by jhit** [comment]
Habe mal einen PR gemacht der das fixed. @Sev03 kannst gerne mal meinen Fork testen, ob der bei dir den fehler auch behebt.
https://github.com/sfxonline/ShyimAttributeTransformer

**Comment by shyim** [comment]
Thanks to @jhit :)
